### ISSUE TITLE
Contributing Guide?

### ISSUE THREAD

**Issue by voltrevo** [leddoo/kibi#1]
Hey! 👋

I've been following this project on YouTube, looks neat.

I'd like to get my feet wet with this thing, I was wondering whether there might be something small I could contribute. Is that something you'd be interested in?

I'm also working on a language. Quite a lot of common ground, also written in rust and also a scripting language that compiles to bytecode and runs in a VM. I was also trying to find a way to reach out and this is what I came up with :).

**Comment by leddoo** [comment]
heyo 👋
thanks for reaching out!
the project is currently on hiatus. i'm now working on a wasm vm instead. once that's ready, i'll revisit kibi's language design, and the compiler will be rewritten to target wasm instead of the bytecode.
i'll let you know, once there's something you could help with 👌
